// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetCoreMVC
{
    public partial class Cities
    {
        public string CityName { get; set; }
        public int StateId { get; set; }
        public int CountryId { get; set; }
        public int Population { get; set; }
    }
}