// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetCoreMVC
{
    public partial class Countries
    {
        public int CountryId { get; set; }
        public string CountryName { get; set; }
    }
}